### ISSUE TITLE
crash after MC schematic converting

### ISSUE THREAD

**Issue by Robsoie** [Uberi/Minetest-WorldEdit#135] opened 2017-06-11 16:13 UTC
Hello,

using the process described here 
https://forum.minetest.net/viewtopic.php?f=12&t=6007

I have been trying to convert schematics files from minecraft into Minetest mts file in order to use worldedit to put them into a world but seems to only results in crash when trying to place the resulting mts with worldedit.

For testing, i downloaded this minecraft schematic as it seemed small enough for me to give a test
https://www.planetminecraft.com/project/medieval-church-3963031/

The MCEdit part + mts export filter from the tutorial seems to work as i obtain a mts , but when i use worldedit , after placing the position 1 block and using 
//mtschemplace nameofmtsfile
Minetest just crash with this error

2017-06-11 17:56:29: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'worldedit_commands' in callback ScriptApiServer::on_chat_message(): deSerializeString: couldn't read all chars
2017-06-11 17:56:29: ERROR[Main]: stack traceback:
2017-06-11 17:56:29: ERROR[Main]: 	[C]: in function 'place_schematic'
2017-06-11 17:56:29: ERROR[Main]: 	...n\..\mods\Minetest-WorldEdit\worldedit_commands\init.lua:1203: in function 'func'
2017-06-11 17:56:29: ERROR[Main]: 	...t-0.4.16-win32-msvc\bin\..\builtin\game\chatcommands.lua:30: in function <...t-0.4.16-win32-msvc\bin\..\builtin\game\chatcommands.lua:9>
2017-06-11 17:56:29: ERROR[Main]: 	...etest-0.4.16-win32-msvc\bin\..\builtin\game\register.lua:412: in function <...etest-0.4.16-win32-msvc\bin\..\builtin\game\register.lua:392>
 
Here is the testor.mts (in a zip file) on dropbox that is a rather small part of the original schematic so its less than 2kb
https://www.dropbox.com/s/abirrnqg87r95tm/testor.zip?dl=0

I exported several other parts of the same minecraft schematic to see if it was some odd result but all of them will simply crash with the same type of error.

I have already placed some mts file through worldedit without a crash, but that's my first attempt at a minecraft schematic converted mts.

**Comment by sfan5** [comment] 2017-06-11 16:36
This is a bug in either Minetest (inlikely) or my program which created the .mts file, WorldEdit just bridges the gap in this case.

**Comment by sfan5** [comment] 2017-06-11 16:57
Seemed to be caused by incorrect line ending conversions on binary files.
Should be fixed now, please redownload the conversion script.

**Closed by sfan5** 2017-06-11 16:57 UTC

**Comment by Robsoie** [comment] 2017-06-11 17:47
Just to confirm i just redownloaded the tomtsschem.py and redid an mts export and this time it worked in worldedit.

thank you
