### ISSUE TITLE
Memory gets overfilled after teleporting and setting the second mark

### ISSUE THREAD

**Issue by HybridDog** [Uberi/Minetest-WorldEdit#114] opened 2016-05-12 18:09 UTC
l tried this more times:
At first execute ```/teleport 2000 0 0```
then ```//pos1```
after that ```/teleport 3000 1000 1000```
and then ```//pos2```

After executing the last chatcommand, minetest gets stuck in some infinite loop or something similar
and if l wait and do not quickly quit minetest, my memory gets filled more and more (no OOM crash happens) and then l need to reboot my pc because of memory problems

Now l got a bad alloc crash:
```
2016-05-12 20:11:10: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2016-05-12 20:11:27: ERROR[Main]: ServerError: Lua: Runtime error from mod 'worldedit_shortcommands' in callback on_chat_message(): std::bad_alloc
2016-05-12 20:11:27: ERROR[Main]: stack traceback:
2016-05-12 20:11:27: ERROR[Main]: 	[C]: in function 'read_from_map'
2016-05-12 20:11:27: ERROR[Main]: 	...minetest/mods/WorldEdit-pack/worldedit_commands/mark.lua:68: in function 'mark_region'
2016-05-12 20:11:27: ERROR[Main]: 	...minetest/mods/WorldEdit-pack/worldedit_commands/mark.lua:48: in function 'mark_pos2'
2016-05-12 20:11:27: ERROR[Main]: 	...minetest/mods/WorldEdit-pack/worldedit_commands/init.lua:189: in function 'func'
2016-05-12 20:11:27: ERROR[Main]: 	/usr/share/minetest/builtin/game/chatcommands.lua:42: in function </usr/share/minetest/builtin/game/chatcommands.lua:30>
2016-05-12 20:11:27: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:369: in function </usr/share/minetest/builtin/game/register.lua:349>
2016-05-12 20:11:27: ACTION[Server]: singleplayer leaves game. List of players: 
```

l took a look at worldedit_commands/mark.lua:
manip:read_from_map is executed for the entire area, the area is big (a billion nodes)
so minetest tries that and fills up all memory,
the bad alloc maybe happened because it tried to reserve/allocate more memory than l have

obviously wordledit can be used to crash the server pc by simply setting pos1 and pos2 far away from each other

l guess l need to forgo my attempt on setting one billion nodes at once using worldedit.
At least l know that ~2.5 million nodes take ~0.3 seconds (with my changes).

**Comment by HybridDog** [comment] 2016-05-12 18:14
Now l got a bad alloc crash:
```
2016-05-12 20:11:10: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2016-05-12 20:11:27: ERROR[Main]: ServerError: Lua: Runtime error from mod 'worldedit_shortcommands' in callback on_chat_message(): std::bad_alloc
2016-05-12 20:11:27: ERROR[Main]: stack traceback:
2016-05-12 20:11:27: ERROR[Main]: 	[C]: in function 'read_from_map'
2016-05-12 20:11:27: ERROR[Main]: 	...minetest/mods/WorldEdit-pack/worldedit_commands/mark.lua:68: in function 'mark_region'
2016-05-12 20:11:27: ERROR[Main]: 	...minetest/mods/WorldEdit-pack/worldedit_commands/mark.lua:48: in function 'mark_pos2'
2016-05-12 20:11:27: ERROR[Main]: 	...minetest/mods/WorldEdit-pack/worldedit_commands/init.lua:189: in function 'func'
2016-05-12 20:11:27: ERROR[Main]: 	/usr/share/minetest/builtin/game/chatcommands.lua:42: in function </usr/share/minetest/builtin/game/chatcommands.lua:30>
2016-05-12 20:11:27: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:369: in function </usr/share/minetest/builtin/game/register.lua:349>
2016-05-12 20:11:27: ACTION[Server]: singleplayer leaves game. List of players: 
```

**Comment by HybridDog** [comment] 2016-05-12 18:21
l took a look at worldedit_commands/mark.lua:
manip:read_from_map is executed for the entire area, the area is big (a billion nodes)
so minetest tries that and fills up all memory,
the bad alloc maybe happened because it tried to reserve/allocate more memory than l have

obviously wordledit can be used to crash the server pc by simply setting pos1 and pos2 far away from each other

**Comment by ShadowNinja** [comment] 2016-05-13 18:11
Bug because you shouldn't be able to OOM the server so easily, even if you have to be a moderator to do it.

**Comment by HybridDog** [comment] 2016-05-14 06:09
@paramat, manip:read_from_map obviously is allowed to take memory without constraint

**Comment by paramat** [comment] 2016-05-14 09:29
I feel the voxelmanip volume, and therefore memory use, should be limited in worldedit not in the voxelmanip. A limit setting that can be set according to server memory available.
The volume you were trying to set was far too big, voxelmanip is meant to process a few chunks at most.

**Comment by HybridDog** [comment] 2016-05-14 10:49
ok, thanks

**Comment by ShadowNinja** [comment] 2016-05-22 05:34
Related: #97

**Comment by HybridDog** [comment] 2016-05-22 09:06
How can you calculate the amount of memory vmanip uses here?

**Comment by paramat** [comment] 2016-05-22 09:31
Not sure. Perhaps just set a reasonable limit for the volume between pos1 and pos2 that causes 1 or 2GB of memory to be used, measured by watching system monitor.

**Comment by HybridDog** [comment] 2016-05-22 10:00
ps can be used to give information about memory:
```
       rss         RSS       resident set size, the non-swapped physical memory that a task has used (inkiloBytes).
       size        SIZE      approximate amount of swap space that would be required if the process were to dirty all writable pages and then be swapped
                             out.  This number is very rough!
       sz          SZ        size in physical pages of the core image of the process.  This includes text, data, and stack space.  Device mappings are
                             currently excluded; this is subject to change.  See vsz and rss.
       vsz         VSZ       virtual memory size of the process in KiB (1024-byte units).  Device mappings are currently excluded; this is subject to
                             change.  (alias vsize).
```
Which one would l need to choose?

**Comment by paramat** [comment] 2016-05-29 04:05
Why closed?

**Comment by HybridDog** [comment] 2016-05-29 07:38
>Why closed?

l closed my PRs and issues that when l click on the buttons, only the active ones are shown.

**Comment by HybridDog** [comment] 2016-05-29 08:42
l tried to measure the memory difference but l didn't have success, it was some small value below 0.
https://github.com/HybridDog/Minetest-WorldEdit/commit/20f5f7c966e005215957b16949ac4c86129998ee

**Comment by sfan5** [comment] 2016-10-12 18:14
duplicate of #97

**Closed by sfan5** 2016-10-12 18:14 UTC
Labels: bug
