### ISSUE TITLE
Constant unknown error when loading schematics

### ISSUE THREAD

**Issue by Alatarius** [Uberi/Minetest-WorldEdit#227] opened 2023-07-09 16:17 UTC
Whenever I try to load a saved schematic it gives me an error "WorldEdit -!- could not open file [schematic]" even though it saved with no problems. [edit] I used [schematic] as a placeholder for the schematic name. I get this error with both the chat commands and the GUI modes of schematic handling. Currently on mt 5.7.0

I followed the directions to the letter and I always get this error when trying to load any schematic. Nothing even shows up in the logs about this error.

**Comment by sfan5** [comment] 2023-07-09 18:43
Did you check if anything appears in debug.txt or standard output of the client/server?

**Comment by Alatarius** [comment] 2023-07-09 18:55
I did check the debug.txt but I will go look at the others since I didn't know there were logs there also

**Comment by Alatarius** [comment] 2023-07-09 19:06
Here is everything in my world folder. What should I be looking for to find error logs?
![Untitled](https://github.com/Uberi/Minetest-WorldEdit/assets/101660302/6aae8c7e-ad46-44c9-957a-2d9f2d364337)

**Comment by sfan5** [comment] 2023-07-10 15:03
debug.txt is not in your world folder, it's next to (not inside) the 'bin' folder.

**Comment by Alatarius** [comment] 2023-07-10 15:51
I did figure out the problem. It's that I have to copy every schematic to each world instead of having a set folder to store all the schematics that every world can access. 

As a suggestion, make a central folder that all the schematics can be stored instead of taking up more space having to copy the schem folder to each world.

**Comment by sfan5** [comment] 2023-07-10 17:15
That makes this a duplicate of #139

**Closed by sfan5** 2023-07-10 17:15 UTC
