### ISSUE TITLE
replace inverse replaced whole marked area

### ISSUE THREAD

**Issue by tchncs** [Uberi/Minetest-WorldEdit#119] opened 2016-07-15 19:01 UTC
Hi there, 

we just replaced a few nodes and then i hitted 'replace inverse'.
Sadly we didn't safed the region before because it didn't replaced the selected node names inverse, no, i replaced the whole area. 

Would be nice if those actions could be reverted be /rollback player.

Regards

**Comment by sfan5** [comment] 2016-07-18 20:01
duplicate of #43

**Closed by sfan5** 2016-07-18 20:01 UTC
