### ISSUE TITLE
Undo and maybe Redo feature

### ISSUE THREAD

**Issue by hunter688** [Uberi/Minetest-WorldEdit#111] opened 2016-03-23 06:37 UTC
As Minecraft user I know and use sk89q's WorldEdit. Many and many times is very useful //undo and sometimes //redo feature. Will be possible add this to Minetest WorldEdit?

**Comment by sfan5** [comment] 2016-03-23 21:30
duplicate of #43

**Closed by sfan5** 2016-03-23 21:30 UTC
Labels: feature request
