### ISSUE TITLE
bad_alloc for not_so_huge sphere (250 nodes radius)

### ISSUE THREAD

**Issue by elettrico** [Uberi/Minetest-WorldEdit#140] opened 2017-07-26 18:07 UTC
In local game on mi laptop (minetest 0.4.16, 8GB ram) when I issue //sphere 250 air I get this:

2017-07-26 14:56:16: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'worldedit_commands' in callback on_chat_message(): std::bad_alloc
2017-07-26 14:56:16: ERROR[Main]: stack traceback:
2017-07-26 14:56:16: ERROR[Main]: 	[C]: in function 'write_to_map'
2017-07-26 14:56:16: ERROR[Main]: 	.../elettrico/.minetest/mods/worldedit/worldedit/common.lua:111: in function 'finish'
2017-07-26 14:56:16: ERROR[Main]: 	...ttrico/.minetest/mods/worldedit/worldedit/primitives.lua:41: in function 'sphere'
2017-07-26 14:56:16: ERROR[Main]: 	...ico/.minetest/mods/worldedit/worldedit_commands/init.lua:492: in function 'callback'
2017-07-26 14:56:16: ERROR[Main]: 	...ico/.minetest/mods/worldedit/worldedit_commands/safe.lua:48: in function 'func'
2017-07-26 14:56:16: ERROR[Main]: 	/usr/share/minetest/builtin/game/chatcommands.lua:30: in function </usr/share/minetest/builtin/game/chatcommands.lua:9>
2017-07-26 14:56:16: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:412: in function </usr/share/minetest/builtin/game/register.lua:392>
AL lib: FreeContext: (0x4de97e0) Deleting 1 Source(s)

If it's as intended or known, is there a way to make huge modifications? What if I want to dig or build something really big?

**Comment by sfan5** [comment] 2017-08-31 13:02
If you're using LuaJIT, this might just be the result of an unfortunate technical limitation.
See [here](https://forum.minetest.net/viewtopic.php?f=3&t=18263)

**Comment by HybridDog** [comment] 2019-04-25 10:13
I get these error messages:
```

2019-04-25 12:01:03: ACTION[Server]: msg to singleplayer: "WorldEdit -!- position 1 set to (108,11,-151)"

2019-04-25 12:01:04: ACTION[Server]: msg to singleplayer: "WorldEdit -!- WARNING: this operation could affect up to 65449847 nodes; type //y to continue or //n to cancel"
2019-04-25 12:01:20: ERROR[Server]: In thread 7f60cb6fd700:
2019-04-25 12:01:20: ERROR[Server]: […]/src/script/cpp_api/s_base.cpp:89: static int ScriptApiBase::luaPanic(lua_State *): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (not enough memory)
Abgebrochen
```
The node ids in lua are stored as doubles in an array. Therefore, when loading a `500x500x500` area with vmanip, the array takes at least `500*500*500*8 B = 1 GB`. The problem does not only happen with LuaJIT because the memory usage grows cubically, e.g. a `2000x2000x2000` are would require at least `64 GB`.
I think this issue is a duplicate of #122.

**Closed** 2019-07-17 00:36 UTC
